version: '3'
services: 
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password
    volumes:
        - ./share/mysql:/var/lib/mysql
  nginx:
    image: nginx:mainline
    volumes: 
      - ./share/nginx:/usr/share/nginx/html
    ports: 
      - "8080:80"
